src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OperationRepository::class)
 */
class Operation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $operation_date;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $operation_type;

    /**
     * @ORM\ManyToOne(targetEntity=Account::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $Account;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getOperationDate(): ?\DateTimeInterface
    {
        return $this->operation_date;
    }

    public function setOperationDate(\DateTimeInterface $operation_date): self
    {
        $this->operation_date = $operation_date;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getOperationType(): ?string
    {
        return $this->operation_type;
    }

    public function setOperationType(string $operation_type): self
    {
        $this->operation_type = $operation_type;

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->Account;
    }

    public function setAccount(?Account $Account): self
    {
        $this->Account = $Account;

        return $this;
    }

}

src/Form/OperationType.php
<?php

namespace App\Form;

use App\Entity\Operation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OperationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('operation_date')
            ->add('amount')
            ->add('operation_type')
            ->add('Account')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Operation::class,
        ]);
    }
}

src/Controller/OperationController.php
<?php

namespace App\Controller;

use App\Entity\Operation;
use App\Form\OperationType;
use App\Repository\OperationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

 /**
  * @IsGranted("IS_AUTHENTICATED_FULLY")
  */

#[Route('/operation')]
class OperationController extends AbstractController
{
    #[Route('/', name: 'operation', methods: ['GET'])]
    public function index(OperationRepository $operationRepository): Response
    {
        return $this->render('operation/index.html.twig', [
            'operations' => $operationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'operation_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $operation = new Operation();
        $form = $this->createForm(OperationType::class, $operation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($operation);
            $entityManager->flush();

            return $this->redirectToRoute('operation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('operation/new.html.twig', [
            'operation' => $operation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'operation_show', methods: ['GET'])]
    public function show(Operation $operation): Response
    {
        return $this->render('operation/show.html.twig', [
            'operation' => $operation,
        ]);
    }

    #[Route('/{id}/edit', name: 'operation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Operation $operation): Response
    {
        $form = $this->createForm(OperationType::class, $operation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('operation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('operation/edit.html.twig', [
            'operation' => $operation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'operation_delete', methods: ['POST'])]
    public function delete(Request $request, Operation $operation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$operation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($operation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('operation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/operation/_delete_form.html.twig
<form method="post" action="{{ path('operation_delete', {'id': operation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ operation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/operation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/operation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Operation{% endblock %}

{% block body %}
    <h1>Edit Operation</h1>

    {{ include('operation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('operation_index') }}">back to list</a>

    {{ include('operation/_delete_form.html.twig') }}
{% endblock %}

templates/operation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Operation index{% endblock %}

{% block body %}
<div class="container pt-3">
    <h2>Operation index</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Operation_date</th>
                <th>Amount</th>
                <th>Operation_type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for operation in operations %}
            <tr>
                <td>{{ operation.id }}</td>
                <td>{{ operation.name }}</td>
                <td>{{ operation.operationDate ? operation.operationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ operation.amount }}</td>
                <td>{{ operation.operationType }}</td>
                <td>
                    <a href="{{ path('operation_show', {'id': operation.id}) }}">show</a>
                    <a href="{{ path('operation_edit', {'id': operation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

    <a href="{{ path('operation_new') }}">Create new</a>
{% endblock %}

templates/operation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Operation{% endblock %}

{% block body %}
    <h1>Create new Operation</h1>

    {{ include('operation/_form.html.twig') }}

    <a href="{{ path('operation_index') }}">back to list</a>
{% endblock %}

templates/operation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Operation{% endblock %}

{% block body %}
    <h1>Operation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ operation.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ operation.name }}</td>
            </tr>
            <tr>
                <th>Operation_date</th>
                <td>{{ operation.operationDate ? operation.operationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ operation.amount }}</td>
            </tr>
            <tr>
                <th>Operation_type</th>
                <td>{{ operation.operationType }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('operation_index') }}">back to list</a>

    <a href="{{ path('operation_edit', {'id': operation.id}) }}">edit</a>

    {{ include('operation/_delete_form.html.twig') }}
{% endblock %}